### ISSUE TITLE
FishySteamworks finalizer causes crash at shutdown

### ISSUE THREAD

**Issue by petergiuntoli** [FirstGearGames/FishySteamworks#6]
I'm noticing that when we close our standalone app we end up hitting a crash inside fishy steamworks when shutting down. This is after the transport has already been shut down once previously. Seems like maybe there's missing state management somewhere but I'm also unsure why there needs to be a finalizer at all, it seems like OnDestroy() should handle cleanup fine.

```
========== OUTPUTTING STACK TRACE ==================

0x00007FFB71E33416 (ntdll) RtlWaitOnAddress
0x00007FFB71DFFCB4 (ntdll) RtlEnterCriticalSection
0x00007FFB71DFFAE2 (ntdll) RtlEnterCriticalSection
0x00007FFAE14DA705 (mono-2.0-bdwgc) mono_profiler_init_etw
0x00007FFAE1425802 (mono-2.0-bdwgc) mono_lookup_icall_symbol
0x000002266554D596 (Mono JIT Code) (wrapper managed-to-native) System.Threading.Thread:GetState (System.Threading.InternalThread)
0x000002266554D4A3 (Mono JIT Code) System.Threading.Thread:get_IsAlive ()
0x00000228D01F4E2B (Mono JIT Code) FishySteamworks.Client.ClientSocket:StopConnection ()
0x00000228D01F4D6B (Mono JIT Code) FishySteamworks.FishySteamworks:StopClient ()
0x00000228D01F4C9B (Mono JIT Code) FishySteamworks.FishySteamworks:StopConnection (bool)
0x00000228D01F4C1A (Mono JIT Code) FishySteamworks.FishySteamworks:Shutdown ()
0x00000228D0204D28 (Mono JIT Code) FishySteamworks.FishySteamworks:Finalize ()
0x00000227CD42B57C (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr)
0x00007FFAE1540D15 (mono-2.0-bdwgc) mono_callspec_cleanup
0x00007FFAE1541DD8 (mono-2.0-bdwgc) mono_gc_finalize_notify
0x00007FFAE1542343 (mono-2.0-bdwgc) mono_gc_finalize_notify
0x00007FFAE14DD34B (mono-2.0-bdwgc) mono_profiler_init_etw
0x00007FFAE14DD526 (mono-2.0-bdwgc) mono_profiler_init_etw
0x00007FFB70F47034 (KERNEL32) BaseThreadInitThunk
0x00007FFB71E22651 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
```

**Comment by FirstGearGames** [comment]
Should be resolved in 2.1.3

**Comment by FirstGearGames** [comment]
Update: version name changed to 4.0.0 to reflect compatibility with FishNet v4. Works with v3 as well.

**Comment by petergiuntoli** [comment]
Forgot about this issue, we ended up removing the finalizer locally as our fix which seems to work. I notice the finalizer still exists, is it necessary?

https://github.com/FirstGearGames/FishySteamworks/blob/main/FishNet/Plugins/FishySteamworks/FishySteamworks.cs#L14-L17

Seems like the OnDestroy() hook is doing the same work.

https://github.com/FirstGearGames/FishySteamworks/blob/main/FishNet/Plugins/FishySteamworks/FishySteamworks.cs#L105-L108

**Comment by FirstGearGames** [comment]
I believe if you do not shut it down on some platforms it will not initialize properly the next time. Or you may have to wait for it to time out. 
The finalizer does still exist but it can only call once now; I suspect your issue was from a double call.
